fixtures:
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref:  "origin/1.8.x"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    xtreemfs: "#{source_dir}"
